default: &default
  adapter: postgresql
  host: localhost
  port: 5434
  min_messages: WARNING
  password: postgres

development: &development
  <<: *default
  database: github_events_counter_development

test:
  <<: *default
  database: github_events_counter_test

production:
  <<: *default
